// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG9u9rcRhFkzziNnxHwcKJc-h1tHr_osM',
    appId: '1:1080183833348:web:93cce75258cf0f73950651',
    messagingSenderId: '1080183833348',
    projectId: 'cravecrush-f927c',
    authDomain: 'cravecrush-f927c.firebaseapp.com',
    storageBucket: 'cravecrush-f927c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4V3FkGY3GU64hXnMOv6NoVtMwH9JJrKs',
    appId: '1:1080183833348:android:a08ff36b938fbc97950651',
    messagingSenderId: '1080183833348',
    projectId: 'cravecrush-f927c',
    storageBucket: 'cravecrush-f927c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdxJNFSkJZlwnID2MQIMzQNq9VnimzLWE',
    appId: '1:1080183833348:ios:fb54ff06c44a31d9950651',
    messagingSenderId: '1080183833348',
    projectId: 'cravecrush-f927c',
    storageBucket: 'cravecrush-f927c.appspot.com',
    iosBundleId: 'com.example.cravecrush',
  );
}
